export const environment = {
  production: false,
  serverUrl: 'http://localhost:3000/projectcaseletsapi/',
  login: 'user/',
  filter: 'filter/',
  metadata: 'metadata/',
  technologies: 'technologies/',
  download: 'download/',
  tools: 'tools/',
  caselet: 'caselet/',
  save: 'save/',
  image: 'image/',
  admin: 'admin/',
  list: 'list/',
  search: 'search',
  tags: 'tags/',
  searchTag: 'searchTag',
  share: 'share/',
  like: 'like/'
};
